### ISSUE TITLE
NodeJS 12 deprecation warning pollutes workflow annotations when this action is used

### ISSUE THREAD

**Issue by webknjaz** [test-summary/action#15]
$sbj. It is scheduled to stop working by summer 2023. Hopefully, switching the value in `action.yml` will be enough.

Refs:
- https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
- https://github.com/ansible-community/ansible-test-gh-action/issues/41

**Comment by dil-gschreiber** [comment]
Can we have a release including this fix, please. 🥺

**Comment by ethomson** [comment]
v2 is now targeting the Node16 runtime.

**Comment by dil-gschreiber** [comment]
tyvm. unfortunately something appears to be wrong with the new release. 

I tracked this issue https://github.com/test-summary/action/issues/18

**Comment by ethomson** [comment]
Thanks I probably tagged the wrong branch in my haste.
