### ISSUE TITLE
v2 broken

### ISSUE THREAD

**Issue by dil-gschreiber** [test-summary/action#18]
Any attempt to use `test-summary/action@v2` results in an error like the following:

```
Error: File not found: '/home/runner/work/_actions/test-summary/action/v2/index.js'
```

I am not an expert on how to release github actions, but I noticed a considerable difference between tags `v2` and `v2.0`  and tags `v1` and `v1.0`:

https://github.com/test-summary/action/tree/v1

vs

https://github.com/test-summary/action/tree/v2

**Comment by ethomson** [comment]
Thanks for reporting @dil-gschreiber - should be fixed now, can you try again?

**Comment by dil-gschreiber** [comment]
works. tx for the quick fix 👍
