### ISSUE TITLE
[Feature] Add dependabot

### ISSUE THREAD

**Issue by andrewbruno** [test-summary/action#29]
We would like to use this action in our organization, but would like better security practices.

Would it be possible to add dependabot

https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates

**Comment by andrewbruno** [comment]
@ethomson love your work, so don't want to take any credit.  I did however fork your project in order to do some security analysis to get it approved for my company.

Dependabot is pretty cool, strongly recommend adding:

![image](https://user-images.githubusercontent.com/7456297/231373816-87c81a95-332d-495d-9af4-9b374aa87fe5.png)

**Comment by ethomson** [comment]
Good call, thanks @andrewbruno -- I added dependabot and codeql

**Comment by andrewbruno** [comment]
Awesome, looking forward to seeing version 2.2

**Comment by ethomson** [comment]
Closing this - let me know if there's anything else that we can do 🙏
