### ISSUE TITLE
Upgrade to Node.js 20 LTS

### ISSUE THREAD

**Issue by RihanArfan** [test-summary/action#39]
On newly released [v2.2](https://github.com/test-summary/action/releases/tag/v2.2), the action runner was upgraded to Node.js v16, which is now EOL. It should be upgraded to v20 LTS. https://endoflife.date/nodejs.

Update: #42 Someone has graciously PR'd an upgrade to Node.js 20, however, keeping this open until a new release is created.

**Comment by vj-hansen** [comment]
https://github.com/test-summary/action/pull/42

**Comment by ralf-ovelgoenne** [comment]
Is it possible to create a new release including the upgrade?

**Comment by hex0cter** [comment]
Same question as above. Please.

**Comment by felixfontein** [comment]
@ethomson could you please release a new version with #42 included?

**Comment by ethomson** [comment]
Should be fixed in the [https://github.com/test-summary/action/releases/tag/v2.3](v2.3) release. Thanks!

**Comment by felixfontein** [comment]
Thank you very much @ethomson!
