### ISSUE TITLE
Release 2.3: Cannot read properties of undefined (reading 'message')

### ISSUE THREAD

**Issue by rschmidt-webit** [test-summary/action#44]
Hey,

Using the new Release creates a error message, when the tests fails:
Cannot read properties of undefined (reading 'message')

Using 2.2 works as expected.

Bye :)

**Comment by andreyfel** [comment]
Getting the same issue. Sems to be caused by this change: https://github.com/test-summary/action/pull/40 @gstokkink would you be able to take a look?

**Comment by thomaschaplin** [comment]
Is there any update to this, please?

@gstokkink I wonder if your PR (https://github.com/test-summary/action/pull/40) requires a specific requirements in the xml files - which not all will have.

cc @ethomson as they approved the PR (https://github.com/test-summary/action/pull/40).

**Comment by austinpray-mixpanel** [comment]
Seeing this as well. Sample Junit file is generated by https://storybook.js.org/ with the `--junit` option
[junit_fail_scrubbed.xml](https://github.com/test-summary/action/files/15084753/junit_fail_scrubbed.xml.txt)

**Comment by JanMa** [comment]
Hello @ethomson is there any update on this issue? I've just updated my project from version `2.1` to `2.3` and started to get the same error

**Comment by ethomson** [comment]
@JanMa - apologies, looking now. 👀 

Unrelated - I notice that you're pinning your actions to SHAs. (Which is a good practice.) Curious if you're doing this manually or using a tool to help?

**Comment by JanMa** [comment]
Thanks for the quick fix @ethomson, I really appreciate it :slightly_smiling_face: 
We're using Dependabot to get updates for our GitHub Actions and it uses the SHA to pin  them

**Comment by ethomson** [comment]
@JanMa Good to know. I just published v2.4, let me know if this doesn't resolve the issue!
